//------------------------------------------------------------------------------
// <auto-generated>
// text. 
//
// textrow text, text
// text, text. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImagePuzzle
{public partial class Default
 {/// <summary>
 /// form1 text. 
 /// </summary>
 /// <remarks>
 /// text. 
 /// textrow text, textfromtexthidetext. 
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlForm form1;}}
